export const USERS = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    address: "123 Main St",
    state: "NY",
    postCode: "10001",
    dateOfBirth: "1990-05-15",
    ssn: "123-45-6789",
    email: "john.doe@mail.com",
    password: "password123",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    address: "456 Elm St",
    state: "CA",
    postCode: "90001",
    dateOfBirth: "1985-10-20",
    ssn: "987-65-4321",
    email: "jane.smith@mail.com",
    password: "securepassword",
  },
  {
    id: "3",
    firstName: "Alice",
    lastName: "Johnson",
    address: "789 Maple St",
    state: "TX",
    postCode: "73301",
    dateOfBirth: "1992-07-30",
    ssn: "456-78-9123",
    email: "alice.johnson@mail.com",
    password: "mypassword",
  },
  {
    id: "4",
    firstName: "Bob",
    lastName: "Brown",
    address: "321 Oak St",
    state: "FL",
    postCode: "33101",
    dateOfBirth: "1988-03-25",
    ssn: "321-54-9876",
    email: "bob.brown@mail.com",
    password: "bobpassword",
  },
  {
    id: "5",
    firstName: "Charlie",
    lastName: "Davis",
    address: "654 Pine St",
    state: "IL",
    postCode: "60601",
    dateOfBirth: "1995-12-12",
    ssn: "654-32-1987",
    email: "charlie.davis@mail.com",
    password: "charlie123",
  },
];
